---
# tasks file for users
- name: Создание пользователя user1
  ansible.builtin.user:
    name: user1
    shell: /bin/bash
    home: "{{ home }}"
    password: "{{ password }}"

- name: Создание директории
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: '0600'
    owner: user1

- name: Копирование ключа из переменной id в файл id_rsa.pub
  copy:
    content: "{{ id }}"
    dest: "{{ home }}/.ssh/id_rsa.pub"
    owner: user1
    group: user1


- name: Добавление ключа из переменной id в authorized_keys пользователя user1
  authorized_key:
    user: user1
    key: "{{ id }}"
    state: present