---
- hosts: srv2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: users
      tags: users

    - role: php
      tags: php

- hosts: srv1
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: users
      tags: users

    - role: http
      tags: http



