---
# tasks file for dnsmasq
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: copy config dnsmasq.conf
  copy:
    src: "{{ role_path }}/files/dnsmasq.conf"
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: copy config resolv.dnsmasq
  copy:
    src: "{{ role_path }}/files/resolv.dnsmasq"
    dest: /etc/resolv.dnsmasq
  notify: Restart dnsmasq

- name: start service dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true
  register: dnsmasq_service_started
