---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

#  vars_files: ./vars/passwd.yml
  roles:
    - role: users
      tags: users

    - role: php
      tags: php

    - role: http
      tags: http



